// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: server-action.proto

package marsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectCorporation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartingHand []*Card `protobuf:"bytes,1,rep,name=starting_hand,json=startingHand,proto3" json:"starting_hand,omitempty"`
	Corps        []*Card `protobuf:"bytes,2,rep,name=corps,proto3" json:"corps,omitempty"`
}

func (x *SelectCorporation) Reset() {
	*x = SelectCorporation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectCorporation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectCorporation) ProtoMessage() {}

func (x *SelectCorporation) ProtoReflect() protoreflect.Message {
	mi := &file_server_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectCorporation.ProtoReflect.Descriptor instead.
func (*SelectCorporation) Descriptor() ([]byte, []int) {
	return file_server_action_proto_rawDescGZIP(), []int{0}
}

func (x *SelectCorporation) GetStartingHand() []*Card {
	if x != nil {
		return x.StartingHand
	}
	return nil
}

func (x *SelectCorporation) GetCorps() []*Card {
	if x != nil {
		return x.Corps
	}
	return nil
}

type BuyCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *BuyCard) Reset() {
	*x = BuyCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyCard) ProtoMessage() {}

func (x *BuyCard) ProtoReflect() protoreflect.Message {
	mi := &file_server_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyCard.ProtoReflect.Descriptor instead.
func (*BuyCard) Descriptor() ([]byte, []int) {
	return file_server_action_proto_rawDescGZIP(), []int{1}
}

func (x *BuyCard) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_server_action_proto protoreflect.FileDescriptor

var file_server_action_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x61, 0x72, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70,
	0x0a, 0x11, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x72,
	0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x63, 0x6f, 0x72,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x72, 0x73, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x70, 0x73,
	0x22, 0x30, 0x0a, 0x07, 0x42, 0x75, 0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x72,
	0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x6d, 0x61, 0x72, 0x73, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_action_proto_rawDescOnce sync.Once
	file_server_action_proto_rawDescData = file_server_action_proto_rawDesc
)

func file_server_action_proto_rawDescGZIP() []byte {
	file_server_action_proto_rawDescOnce.Do(func() {
		file_server_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_action_proto_rawDescData)
	})
	return file_server_action_proto_rawDescData
}

var file_server_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_action_proto_goTypes = []interface{}{
	(*SelectCorporation)(nil), // 0: marsproto.SelectCorporation
	(*BuyCard)(nil),           // 1: marsproto.BuyCard
	(*Card)(nil),              // 2: marsproto.Card
}
var file_server_action_proto_depIdxs = []int32{
	2, // 0: marsproto.SelectCorporation.starting_hand:type_name -> marsproto.Card
	2, // 1: marsproto.SelectCorporation.corps:type_name -> marsproto.Card
	2, // 2: marsproto.BuyCard.cards:type_name -> marsproto.Card
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_action_proto_init() }
func file_server_action_proto_init() {
	if File_server_action_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectCorporation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_action_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_action_proto_goTypes,
		DependencyIndexes: file_server_action_proto_depIdxs,
		MessageInfos:      file_server_action_proto_msgTypes,
	}.Build()
	File_server_action_proto = out.File
	file_server_action_proto_rawDesc = nil
	file_server_action_proto_goTypes = nil
	file_server_action_proto_depIdxs = nil
}
