// source: client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.marsproto.ActionResponse', null, global);
goog.exportSymbol('proto.marsproto.ClientMessage', null, global);
goog.exportSymbol('proto.marsproto.ClientMessage.DataCase', null, global);
goog.exportSymbol('proto.marsproto.ReadRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.marsproto.ClientMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.marsproto.ClientMessage.oneofGroups_);
};
goog.inherits(proto.marsproto.ClientMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.marsproto.ClientMessage.displayName = 'proto.marsproto.ClientMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.marsproto.ActionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.marsproto.ActionResponse.repeatedFields_, null);
};
goog.inherits(proto.marsproto.ActionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.marsproto.ActionResponse.displayName = 'proto.marsproto.ActionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.marsproto.ReadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.marsproto.ReadRequest.repeatedFields_, null);
};
goog.inherits(proto.marsproto.ReadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.marsproto.ReadRequest.displayName = 'proto.marsproto.ReadRequest';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.marsproto.ClientMessage.oneofGroups_ = [[100,101]];

/**
 * @enum {number}
 */
proto.marsproto.ClientMessage.DataCase = {
  DATA_NOT_SET: 0,
  ACT_RESPONSE: 100,
  READ_REQUEST: 101
};

/**
 * @return {proto.marsproto.ClientMessage.DataCase}
 */
proto.marsproto.ClientMessage.prototype.getDataCase = function() {
  return /** @type {proto.marsproto.ClientMessage.DataCase} */(jspb.Message.computeOneofCase(this, proto.marsproto.ClientMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.marsproto.ClientMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.marsproto.ClientMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.marsproto.ClientMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ClientMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    actResponse: (f = msg.getActResponse()) && proto.marsproto.ActionResponse.toObject(includeInstance, f),
    readRequest: (f = msg.getReadRequest()) && proto.marsproto.ReadRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.marsproto.ClientMessage}
 */
proto.marsproto.ClientMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.marsproto.ClientMessage;
  return proto.marsproto.ClientMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.marsproto.ClientMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.marsproto.ClientMessage}
 */
proto.marsproto.ClientMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 100:
      var value = new proto.marsproto.ActionResponse;
      reader.readMessage(value,proto.marsproto.ActionResponse.deserializeBinaryFromReader);
      msg.setActResponse(value);
      break;
    case 101:
      var value = new proto.marsproto.ReadRequest;
      reader.readMessage(value,proto.marsproto.ReadRequest.deserializeBinaryFromReader);
      msg.setReadRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.marsproto.ClientMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.marsproto.ClientMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.marsproto.ClientMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ClientMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActResponse();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.marsproto.ActionResponse.serializeBinaryToWriter
    );
  }
  f = message.getReadRequest();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.marsproto.ReadRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional ActionResponse act_response = 100;
 * @return {?proto.marsproto.ActionResponse}
 */
proto.marsproto.ClientMessage.prototype.getActResponse = function() {
  return /** @type{?proto.marsproto.ActionResponse} */ (
    jspb.Message.getWrapperField(this, proto.marsproto.ActionResponse, 100));
};


/**
 * @param {?proto.marsproto.ActionResponse|undefined} value
 * @return {!proto.marsproto.ClientMessage} returns this
*/
proto.marsproto.ClientMessage.prototype.setActResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.marsproto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.marsproto.ClientMessage} returns this
 */
proto.marsproto.ClientMessage.prototype.clearActResponse = function() {
  return this.setActResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.marsproto.ClientMessage.prototype.hasActResponse = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional ReadRequest read_request = 101;
 * @return {?proto.marsproto.ReadRequest}
 */
proto.marsproto.ClientMessage.prototype.getReadRequest = function() {
  return /** @type{?proto.marsproto.ReadRequest} */ (
    jspb.Message.getWrapperField(this, proto.marsproto.ReadRequest, 101));
};


/**
 * @param {?proto.marsproto.ReadRequest|undefined} value
 * @return {!proto.marsproto.ClientMessage} returns this
*/
proto.marsproto.ClientMessage.prototype.setReadRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.marsproto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.marsproto.ClientMessage} returns this
 */
proto.marsproto.ClientMessage.prototype.clearReadRequest = function() {
  return this.setReadRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.marsproto.ClientMessage.prototype.hasReadRequest = function() {
  return jspb.Message.getField(this, 101) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.marsproto.ActionResponse.repeatedFields_ = [101];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.marsproto.ActionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.marsproto.ActionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.marsproto.ActionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ActionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    player: jspb.Message.getFieldWithDefault(msg, 2, 0),
    value: jspb.Message.getFieldWithDefault(msg, 100, 0),
    listList: (f = jspb.Message.getRepeatedField(msg, 101)) == null ? undefined : f,
    mapMap: (f = msg.getMapMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.marsproto.ActionResponse}
 */
proto.marsproto.ActionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.marsproto.ActionResponse;
  return proto.marsproto.ActionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.marsproto.ActionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.marsproto.ActionResponse}
 */
proto.marsproto.ActionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPlayer(value);
      break;
    case 100:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    case 101:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setListList(value);
      break;
    case 102:
      var value = msg.getMapMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.marsproto.ActionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.marsproto.ActionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.marsproto.ActionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ActionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      100,
      f
    );
  }
  f = message.getListList();
  if (f.length > 0) {
    writer.writePackedInt32(
      101,
      f
    );
  }
  f = message.getMapMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(102, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.marsproto.ActionResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 player = 2;
 * @return {number}
 */
proto.marsproto.ActionResponse.prototype.getPlayer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 value = 100;
 * @return {number}
 */
proto.marsproto.ActionResponse.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 100, value);
};


/**
 * repeated int32 list = 101;
 * @return {!Array<number>}
 */
proto.marsproto.ActionResponse.prototype.getListList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 101));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.setListList = function(value) {
  return jspb.Message.setField(this, 101, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.addList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 101, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.clearListList = function() {
  return this.setListList([]);
};


/**
 * map<string, int32> map = 102;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.marsproto.ActionResponse.prototype.getMapMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 102, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.marsproto.ActionResponse} returns this
 */
proto.marsproto.ActionResponse.prototype.clearMapMap = function() {
  this.getMapMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.marsproto.ReadRequest.repeatedFields_ = [201];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.marsproto.ReadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.marsproto.ReadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.marsproto.ReadRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ReadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    player: jspb.Message.getFieldWithDefault(msg, 2, 0),
    resource: jspb.Message.getFieldWithDefault(msg, 100, ""),
    value: jspb.Message.getFieldWithDefault(msg, 200, 0),
    listList: (f = jspb.Message.getRepeatedField(msg, 201)) == null ? undefined : f,
    mapMap: (f = msg.getMapMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.marsproto.ReadRequest}
 */
proto.marsproto.ReadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.marsproto.ReadRequest;
  return proto.marsproto.ReadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.marsproto.ReadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.marsproto.ReadRequest}
 */
proto.marsproto.ReadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPlayer(value);
      break;
    case 100:
      var value = /** @type {string} */ (reader.readString());
      msg.setResource(value);
      break;
    case 200:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    case 201:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setListList(value);
      break;
    case 202:
      var value = msg.getMapMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt32, null, "", 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.marsproto.ReadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.marsproto.ReadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.marsproto.ReadRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ReadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getResource();
  if (f.length > 0) {
    writer.writeString(
      100,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      200,
      f
    );
  }
  f = message.getListList();
  if (f.length > 0) {
    writer.writePackedInt32(
      201,
      f
    );
  }
  f = message.getMapMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(202, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt32);
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.marsproto.ReadRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 player = 2;
 * @return {number}
 */
proto.marsproto.ReadRequest.prototype.getPlayer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string resource = 100;
 * @return {string}
 */
proto.marsproto.ReadRequest.prototype.getResource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 100, ""));
};


/**
 * @param {string} value
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.setResource = function(value) {
  return jspb.Message.setProto3StringField(this, 100, value);
};


/**
 * optional int32 value = 200;
 * @return {number}
 */
proto.marsproto.ReadRequest.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 200, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 200, value);
};


/**
 * repeated int32 list = 201;
 * @return {!Array<number>}
 */
proto.marsproto.ReadRequest.prototype.getListList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 201));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.setListList = function(value) {
  return jspb.Message.setField(this, 201, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.addList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 201, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.clearListList = function() {
  return this.setListList([]);
};


/**
 * map<string, int32> map = 202;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.marsproto.ReadRequest.prototype.getMapMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 202, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.marsproto.ReadRequest} returns this
 */
proto.marsproto.ReadRequest.prototype.clearMapMap = function() {
  this.getMapMap().clear();
  return this;};


goog.object.extend(exports, proto.marsproto);
