// source: server.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.marsproto.ServerMessage');
goog.provide('proto.marsproto.ServerMessage.DataCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.marsproto.Acknowledge');
goog.require('proto.marsproto.ActionRequest');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.marsproto.ServerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.marsproto.ServerMessage.oneofGroups_);
};
goog.inherits(proto.marsproto.ServerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.marsproto.ServerMessage.displayName = 'proto.marsproto.ServerMessage';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.marsproto.ServerMessage.oneofGroups_ = [[100,101]];

/**
 * @enum {number}
 */
proto.marsproto.ServerMessage.DataCase = {
  DATA_NOT_SET: 0,
  ACK: 100,
  REQUEST: 101
};

/**
 * @return {proto.marsproto.ServerMessage.DataCase}
 */
proto.marsproto.ServerMessage.prototype.getDataCase = function() {
  return /** @type {proto.marsproto.ServerMessage.DataCase} */(jspb.Message.computeOneofCase(this, proto.marsproto.ServerMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.marsproto.ServerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.marsproto.ServerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.marsproto.ServerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ServerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    player: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ack: (f = msg.getAck()) && proto.marsproto.Acknowledge.toObject(includeInstance, f),
    request: (f = msg.getRequest()) && proto.marsproto.ActionRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.marsproto.ServerMessage}
 */
proto.marsproto.ServerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.marsproto.ServerMessage;
  return proto.marsproto.ServerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.marsproto.ServerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.marsproto.ServerMessage}
 */
proto.marsproto.ServerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayer(value);
      break;
    case 100:
      var value = new proto.marsproto.Acknowledge;
      reader.readMessage(value,proto.marsproto.Acknowledge.deserializeBinaryFromReader);
      msg.setAck(value);
      break;
    case 101:
      var value = new proto.marsproto.ActionRequest;
      reader.readMessage(value,proto.marsproto.ActionRequest.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.marsproto.ServerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.marsproto.ServerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.marsproto.ServerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.marsproto.ServerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAck();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.marsproto.Acknowledge.serializeBinaryToWriter
    );
  }
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.marsproto.ActionRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.marsproto.ServerMessage.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ServerMessage} returns this
 */
proto.marsproto.ServerMessage.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 player = 2;
 * @return {number}
 */
proto.marsproto.ServerMessage.prototype.getPlayer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.marsproto.ServerMessage} returns this
 */
proto.marsproto.ServerMessage.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Acknowledge ack = 100;
 * @return {?proto.marsproto.Acknowledge}
 */
proto.marsproto.ServerMessage.prototype.getAck = function() {
  return /** @type{?proto.marsproto.Acknowledge} */ (
    jspb.Message.getWrapperField(this, proto.marsproto.Acknowledge, 100));
};


/**
 * @param {?proto.marsproto.Acknowledge|undefined} value
 * @return {!proto.marsproto.ServerMessage} returns this
*/
proto.marsproto.ServerMessage.prototype.setAck = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.marsproto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.marsproto.ServerMessage} returns this
 */
proto.marsproto.ServerMessage.prototype.clearAck = function() {
  return this.setAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.marsproto.ServerMessage.prototype.hasAck = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional ActionRequest request = 101;
 * @return {?proto.marsproto.ActionRequest}
 */
proto.marsproto.ServerMessage.prototype.getRequest = function() {
  return /** @type{?proto.marsproto.ActionRequest} */ (
    jspb.Message.getWrapperField(this, proto.marsproto.ActionRequest, 101));
};


/**
 * @param {?proto.marsproto.ActionRequest|undefined} value
 * @return {!proto.marsproto.ServerMessage} returns this
*/
proto.marsproto.ServerMessage.prototype.setRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.marsproto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.marsproto.ServerMessage} returns this
 */
proto.marsproto.ServerMessage.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.marsproto.ServerMessage.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 101) != null;
};


